name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalender.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: debjeetxyz
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.dashboard.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: debjeetxyz
          template: classic
          base: header, activity, community, repositories
          
          # Plugin configurations for your custom layout
          plugin_languages: yes
          plugin_languages_details: bytes, percentage
          plugin_languages_ignored: html
          plugin_languages_limit: 8
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes
          
          plugin_introduction: yes
